# Generated by Django 4.0.1 on 2022-01-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='examcenter',
            fields=[
                ('ExamCenterID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('governorate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='proctor',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('ExamCenterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.examcenter')),
            ],
        ),
    ]
